=== readium/speech/voices.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://readium.org/speech/voices.schema.json",
  "title": "Recommended voices for TTS",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "language": {
      "type": "string"
    },
    "defaultRegion": {
      "type": "string"
    },
    "testUtterance": {
      "type": "string"
    },
    "voices": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "label": {
            "type": "string",
            "description": "Provides a human-friendly label for each voice."
          },
          "name": {
            "type": "string",
            "description": "Identifies voices, as returned by the Web Speech API."
          },
          "localizedName": {
            "type": "string",
            "description": "Identifies the string pattern used to localized a given voice.",
            "enum": [
              "android",
              "apple"
            ]
          },
          "note": {
            "type": "string"
          },
          "altNames": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Alternate names for a given voice. Only useful for Apple voices."
            }
          },
          "nativeID": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Identifiers used by the native API of the platform for a specific voice."
            }
          },
          "language": {
            "type": "string",
            "description": "BCP-47 language tag that identifies the language of a voice."
          },
          "altLanguage": {
            "type": "string",
            "description": "Alternative BCP-47 language tag, mostly used for deprecated values."
          },
          "otherLanguages": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "multiLingual": {
            "type": "boolean",
            "description": "Identifies voices that are capable of handling multiple languages, even if it means that the voice itself will change. Only available on Microsoft Natural voices for now.",
            "default": false
          },
          "gender": {
            "type": "string",
            "description": "Identifies the gender of a voice.",
            "enum": [
              "neutral",
              "female",
              "male"
            ]
          },
          "children": {
            "type": "boolean",
            "description": "Indicates if the voice is a children voice.",
            "default": false
          },
          "quality": {
            "type": "array",
            "description": "Quality available for the variants of a given voice",
            "items": {
              "type": "string",
              "enum": [
                "veryLow",
                "low",
                "normal",
                "high",
                "veryHigh"
              ]
            }
          },
          "rate": {
            "type": "number",
            "description": "Default recommended speed rate for a voice.",
            "minimum": 0.1,
            "maximum": 10,
            "default": 1
          },
          "pitch": {
            "type": "number",
            "description": "Default recommended pitch rate for a voice.",
            "minimum": 0,
            "maximum": 2,
            "default": 1
          },
          "controls": {
            "type": "object",
            "description": "Indicates which controls are available for a given voice.",
            "additionalProperties": false,
            "properties": {
              "boundary": {
                "description": "Indicates whether a voice returns boundary events.",
                "type": "boolean",
                "default": true
              },
              "pitch": {
                "description": "Indicates whether a voice can be pitch adjusted.",
                "type": "boolean",
                "default": true
              }
            }
          },
          "os": {
            "type": "array",
            "description": "List of operating systems in which a voice is available.",
            "minItems": 1,
            "items": {
              "type": "string",
              "enum": [
                "Android",
                "ChromeOS",
                "iOS",
                "iPadOS",
                "macOS",
                "Windows"
              ]
            }
          },
          "browser": {
            "type": "array",
            "description": "List of Web browsers in which a voice is available.",
            "minItems": 1,
            "items": {
              "type": "string",
              "enum": [
                "ChromeDesktop",
                "Edge",
                "Firefox",
                "Safari"
              ]
            }
          },
          "preloaded": {
            "type": "boolean",
            "description": "Indicates that a voice is preloaded in all OS and browsers that have been identified.",
            "default": false
          }
        },
        "required": [
          "name"
        ]
      }
    }
  },
  "required": [
    "voices"
  ]
}

=== readium/speech/json/ro.json
{
  "language": "ro",
  "defaultRegion": "ro-RO",
  "testUtterance": "Buna ziua, ma numesc {name} si sunt o voce romaneasca.",
  "voices": [
    {
      "label": "Alina",
      "name": "Microsoft Alina Online (Natural) - Romanian (Romania)",
      "language": "ro-RO",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Emil",
      "name": "Microsoft Emil Online (Natural) - Romanian (Romania)",
      "language": "ro-RO",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Ioana",
      "name": "Ioana",
      "localizedName": "apple",
      "language": "ro-RO",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Andrei",
      "name": "Microsoft Andrei - Romanian (Romania)",
      "language": "ro-RO",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Voce feminină",
      "name": "Android Speech Recognition and Synthesis from Google ro-ro-x-vfv-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ro-ro-x-vfv-local",
        "Android Speech Recognition and Synthesis from Google ro-RO-language"
      ],
      "nativeID": [
        "ro-ro-x-vfv-network",
        "ro-ro-x-vfv-local"
      ],
      "language": "ro-RO",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/hi.json
{
  "language": "hi",
  "defaultRegion": "hi-IN",
  "testUtterance": "नमस्कार, मेरा नाम {name} है और मैं एक हिंदी आवाज़ हूँ।",
  "voices": [
    {
      "label": "Swara",
      "name": "Microsoft Swara Online (Natural) - Hindi (India)",
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Madhur",
      "name": "Microsoft Madhur Online (Natural) - Hindi (India)",
      "language": "hi-IN",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "महिला Google आवाज़",
      "name": "Google हिन्दी",
      "note": "This voice is pre-loaded in Chrome on desktop. Utterances that are longer than 14 seconds long can trigger a bug with this voice, check the notes in the project's README for more information.",
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "controls": {
        "boundary": false
      },
      "browser": [
        "ChromeDesktop"
      ],
      "preloaded": true
    },
    {
      "label": "Kiyara",
      "name": "Kiyara",
      "localizedName": "apple",
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "low",
        "normal",
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Lekha",
      "name": "Lekha",
      "localizedName": "apple",
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Neel",
      "name": "Neel",
      "localizedName": "apple",
      "language": "hi-IN",
      "gender": "male",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Kalpana",
      "name": "Microsoft Kalpana - Hindi (India)",
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Hemant",
      "name": "Microsoft Hemant - Hindi (India)",
      "language": "hi-IN",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "महिला आवाज़ 1",
      "name": "Google हिन्दी 1 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google hi-in-x-hia-network",
        "Chrome OS हिन्दी 2",
        "Android Speech Recognition and Synthesis from Google hi-in-x-hia-local",
        "Android Speech Recognition and Synthesis from Google hi-IN-language"
      ],
      "nativeID": [
        "hi-in-x-hia-network",
        "hi-in-x-hia-local"
      ],
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "महिला आवाज़ 2",
      "name": "Google हिन्दी 2 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google hi-in-x-hic-network",
        "Chrome OS हिन्दी 3",
        "Android Speech Recognition and Synthesis from Google hi-in-x-hic-local"
      ],
      "nativeID": [
        "hi-in-x-hic-network",
        "hi-in-x-hic-local"
      ],
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "महिला आवाज़ 3",
      "name": "Chrome OS हिन्दी 1",
      "language": "hi-IN",
      "gender": "female",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "पुरुष आवाज 1",
      "name": "Google हिन्दी 3 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google hi-in-x-hid-network",
        "Chrome OS हिन्दी 4",
        "Android Speech Recognition and Synthesis from Google hi-in-x-hid-local"
      ],
      "nativeID": [
        "hi-in-x-hid-network",
        "hi-in-x-hid-local"
      ],
      "language": "hi-IN",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "पुरुष आवाज 2",
      "name": "Google हिन्दी 4 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google hi-in-x-hie-network",
        "Chrome OS हिन्दी 5",
        "Android Speech Recognition and Synthesis from Google hi-in-x-hie-local"
      ],
      "nativeID": [
        "hi-in-x-hie-network",
        "hi-in-x-hie-local"
      ],
      "language": "hi-IN",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/yue.json
{
  "language": "yue",
  "defaultRegion": "yue-HK",
  "testUtterance": "你好，我叫 {name}，係越中文聲。",
  "voices": [
    {
      "label": "HiuGaai",
      "name": "Microsoft HiuGaai Online (Natural) - Chinese (Cantonese Traditional)",
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "HiuMaan",
      "name": "Microsoft HiuMaan Online (Natural) - Chinese (Hong Kong SAR)",
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "WanLung",
      "name": "Microsoft WanLung Online (Natural) - Chinese (Hong Kong SAR)",
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Google 女聲",
      "name": "Google 粤語（香港）",
      "note": "This voice is pre-loaded in Chrome on desktop. Utterances that are longer than 14 seconds long can trigger a bug with this voice, check the notes in the project's README for more information.",
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "controls": {
        "boundary": false
      },
      "browser": [
        "ChromeDesktop"
      ],
      "preloaded": true
    },
    {
      "label": "Sinji",
      "name": "Sinji",
      "localizedName": "apple",
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "female",
      "quality": [
        "low",
        "normal",
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Aasing",
      "name": "Aasing",
      "localizedName": "apple",
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Tracy",
      "name": "Microsoft Tracy - Chinese (Traditional, Hong Kong S.A.R.)",
      "language": "cmn-HK",
      "altLanguage": "zh-HK",
      "gender": "female",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Danny",
      "name": "Microsoft Danny - Chinese (Traditional, Hong Kong S.A.R.)",
      "language": "cmn-HK",
      "altLanguage": "zh-HK",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "女聲1",
      "name": "Android Speech Recognition and Synthesis from Google yue-hk-x-jar-network",
      "altNames": [
        "Chrome OS 粵語 1",
        "Android Speech Recognition and Synthesis from Google yue-HK-x-jar-local",
        "Android Speech Recognition and Synthesis from Google yue-HK-language"
      ],
      "nativeID": [
        "yue-hk-x-jar-network",
        "yue-hk-x-jar-local"
      ],
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "女聲2",
      "name": "Android Speech Recognition and Synthesis from Google yue-hk-x-yuc-network",
      "altNames": [
        "Chrome OS 粵語 2",
        "Android Speech Recognition and Synthesis from Google yue-HK-x-yuc-local"
      ],
      "nativeID": [
        "yue-hk-x-yuc-network",
        "yue-hk-x-yuc-local"
      ],
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "男聲1",
      "name": "Android Speech Recognition and Synthesis from Google yue-hk-x-yud-network",
      "altNames": [
        "Chrome OS 粵語 3",
        "Android Speech Recognition and Synthesis from Google yue-HK-x-yud-local"
      ],
      "nativeID": [
        "yue-hk-x-yud-network",
        "yue-hk-x-yud-local"
      ],
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "男聲2",
      "name": "Android Speech Recognition and Synthesis from Google yue-hk-x-yue-network",
      "altNames": [
        "Chrome OS 粵語 5",
        "Android Speech Recognition and Synthesis from Google yue-HK-x-yue-local"
      ],
      "nativeID": [
        "yue-hk-x-yue-network",
        "yue-hk-x-yue-local"
      ],
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "男聲3",
      "name": "Android Speech Recognition and Synthesis from Google yue-hk-x-yuf-network",
      "altNames": [
        "Chrome OS 粵語 5",
        "Android Speech Recognition and Synthesis from Google yue-HK-x-yuf-local"
      ],
      "nativeID": [
        "yue-hk-x-yuf-network",
        "yue-hk-x-yuf-local"
      ],
      "language": "yue-HK",
      "altLanguage": "zh-HK",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/ca.json
{
  "language": "ca",
  "defaultRegion": "ca-ES",
  "testUtterance": "Hola, em dic {name} i sóc una veu catalana",
  "voices": [
    {
      "label": "Joana (Català)",
      "name": "Microsoft Joana Online (Natural) - Catalan",
      "language": "ca-ES",
      "otherLanguages": [
        "es"
      ],
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Enric (Català)",
      "name": "Microsoft Enric Online (Natural) - Catalan",
      "language": "ca-ES",
      "otherLanguages": [
        "es"
      ],
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Montse (Català)",
      "name": "Montse",
      "localizedName": "apple",
      "language": "ca-ES",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Pau (Valencià)",
      "name": "Pau",
      "localizedName": "apple",
      "language": "ca-ES-u-sd-esvc",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Jordi (Català)",
      "name": "Jordi",
      "localizedName": "apple",
      "language": "ca-ES",
      "gender": "male",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Herena (Català)",
      "name": "Microsoft Herena - Catalan (Spain)",
      "language": "ca-ES",
      "gender": "female",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Veu femenina catalana",
      "name": "Android Speech Recognition and Synthesis from Google ca-es-x-caf-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ca-es-x-caf-local",
        "Android Speech Recognition and Synthesis from Google ca-ES-language"
      ],
      "nativeID": [
        "ca-es-x-caf-network",
        "ca-es-x-caf-local"
      ],
      "language": "ca-ES",
      "otherLanguages": [
        "es"
      ],
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/bg.json
{
  "language": "bg",
  "defaultRegion": "bg-BG",
  "testUtterance": "Здравейте, казвам се {name} и съм български глас.",
  "voices": [
    {
      "label": "Kalina",
      "name": "Microsoft Kalina Online (Natural) - Bulgarian (Bulgaria)",
      "language": "bg-BG",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Borislav",
      "name": "Microsoft Borislav Online (Natural) - Bulgarian (Bulgaria)",
      "language": "bg-BG",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Daria",
      "name": "Daria",
      "localizedName": "apple",
      "language": "bg-BG",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Ivan",
      "name": "Microsoft Ivan - Bulgarian (Bulgaria)",
      "language": "bg-BG",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Женски глас",
      "name": "Android Speech Recognition and Synthesis from Google bg-bg-x-ifk-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google bg-bg-x-ifk-local",
        "Android Speech Recognition and Synthesis from Google bg-bg-language"
      ],
      "nativeID": [
        "bg-bg-x-ifk-network",
        "bg-bg-x-ifk-local"
      ],
      "language": "bg-BG",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/th.json
{
  "language": "th",
  "defaultRegion": "th-TH",
  "testUtterance": "สวัสดีค่ะ ฉันชื่อ {name} และฉันเป็นคนมีเสียงภาษาไทย",
  "voices": [
    {
      "label": "Premwadee",
      "name": "Microsoft Premwadee Online (Natural) - Thai (Thailand)",
      "language": "th-TH",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Niwat",
      "name": "Microsoft Niwat Online (Natural) - Thai (Thailand)",
      "language": "th-TH",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Narisa",
      "name": "Narisa",
      "localizedName": "apple",
      "language": "th-TH",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Kanya",
      "name": "Kanya",
      "localizedName": "apple",
      "language": "th-TH",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Pattara",
      "name": "Microsoft Pattara - Thai (Thailand)",
      "language": "th-TH",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "เสียงผู้หญิง",
      "name": "Google ไทย (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google th-th-x-mol-network",
        "Chrome OS ไทย",
        "Android Speech Recognition and Synthesis from Google th-th-x-mol-local",
        "Android Speech Recognition and Synthesis from Google th-TH-language"
      ],
      "nativeID": [
        "th-th-x-mol-network",
        "th-th-x-mol-local"
      ],
      "language": "th-TH",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}
