=== readium/speech/voices.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://readium.org/speech/voices.schema.json",
  "title": "Recommended voices for TTS",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "language": {
      "type": "string"
    },
    "defaultRegion": {
      "type": "string"
    },
    "testUtterance": {
      "type": "string"
    },
    "voices": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "label": {
            "type": "string",
            "description": "Provides a human-friendly label for each voice."
          },
          "name": {
            "type": "string",
            "description": "Identifies voices, as returned by the Web Speech API."
          },
          "localizedName": {
            "type": "string",
            "description": "Identifies the string pattern used to localized a given voice.",
            "enum": [
              "android",
              "apple"
            ]
          },
          "note": {
            "type": "string"
          },
          "altNames": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Alternate names for a given voice. Only useful for Apple voices."
            }
          },
          "nativeID": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Identifiers used by the native API of the platform for a specific voice."
            }
          },
          "language": {
            "type": "string",
            "description": "BCP-47 language tag that identifies the language of a voice."
          },
          "altLanguage": {
            "type": "string",
            "description": "Alternative BCP-47 language tag, mostly used for deprecated values."
          },
          "otherLanguages": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "multiLingual": {
            "type": "boolean",
            "description": "Identifies voices that are capable of handling multiple languages, even if it means that the voice itself will change. Only available on Microsoft Natural voices for now.",
            "default": false
          },
          "gender": {
            "type": "string",
            "description": "Identifies the gender of a voice.",
            "enum": [
              "neutral",
              "female",
              "male"
            ]
          },
          "children": {
            "type": "boolean",
            "description": "Indicates if the voice is a children voice.",
            "default": false
          },
          "quality": {
            "type": "array",
            "description": "Quality available for the variants of a given voice",
            "items": {
              "type": "string",
              "enum": [
                "veryLow",
                "low",
                "normal",
                "high",
                "veryHigh"
              ]
            }
          },
          "rate": {
            "type": "number",
            "description": "Default recommended speed rate for a voice.",
            "minimum": 0.1,
            "maximum": 10,
            "default": 1
          },
          "pitch": {
            "type": "number",
            "description": "Default recommended pitch rate for a voice.",
            "minimum": 0,
            "maximum": 2,
            "default": 1
          },
          "controls": {
            "type": "object",
            "description": "Indicates which controls are available for a given voice.",
            "additionalProperties": false,
            "properties": {
              "boundary": {
                "description": "Indicates whether a voice returns boundary events.",
                "type": "boolean",
                "default": true
              },
              "pitch": {
                "description": "Indicates whether a voice can be pitch adjusted.",
                "type": "boolean",
                "default": true
              }
            }
          },
          "os": {
            "type": "array",
            "description": "List of operating systems in which a voice is available.",
            "minItems": 1,
            "items": {
              "type": "string",
              "enum": [
                "Android",
                "ChromeOS",
                "iOS",
                "iPadOS",
                "macOS",
                "Windows"
              ]
            }
          },
          "browser": {
            "type": "array",
            "description": "List of Web browsers in which a voice is available.",
            "minItems": 1,
            "items": {
              "type": "string",
              "enum": [
                "ChromeDesktop",
                "Edge",
                "Firefox",
                "Safari"
              ]
            }
          },
          "preloaded": {
            "type": "boolean",
            "description": "Indicates that a voice is preloaded in all OS and browsers that have been identified.",
            "default": false
          }
        },
        "required": [
          "name"
        ]
      }
    }
  },
  "required": [
    "voices"
  ]
}

=== readium/speech/json/bn.json
{
  "language": "bn",
  "defaultRegion": "bn-IN",
  "testUtterance": "হ্যালো, আমার নাম {name} এবং আমি একজন বাংলা ভয়েস।",
  "voices": [
    {
      "label": "Tanishaa",
      "name": "Microsoft Tanishaa Online (Natural) - Bengali (India)",
      "language": "bn-IN",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Bashkar",
      "name": "Microsoft Bashkar Online (Natural) - Bangla (India)",
      "language": "bn-IN",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Nabanita",
      "name": "Microsoft Nabanita Online (Natural) - Bangla (Bangladesh)",
      "language": "bn-BD",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Pradeep",
      "name": "Microsoft Pradeep Online (Natural) - Bangla (Bangladesh)",
      "language": "bn-BD",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Piya",
      "name": "Piya",
      "localizedName": "apple",
      "language": "bn-IN",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "মহিলা কণ্ঠস্বর 1",
      "name": "Android Speech Recognition and Synthesis from Google bn-in-x-bnf-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google bn-in-x-bnf-local",
        "Android Speech Recognition and Synthesis from Google bn-IN-language"
      ],
      "nativeID": [
        "bn-in-x-bnf-network",
        "bn-in-x-bnf-local"
      ],
      "language": "bn-IN",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "মহিলা কণ্ঠস্বর 2",
      "name": "Android Speech Recognition and Synthesis from Google bn-in-x-bnx-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google bn-in-x-bnx-local"
      ],
      "nativeID": [
        "bn-in-x-bnx-network",
        "bn-in-x-bnx-local"
      ],
      "language": "bn-IN",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "পুরুষ কন্ঠ 1",
      "name": "Android Speech Recognition and Synthesis from Google bn-in-x-bin-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google bn-in-x-bin-local"
      ],
      "nativeID": [
        "bn-in-x-bin-network",
        "bn-in-x-bin-local"
      ],
      "language": "bn-IN",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "পুরুষ কন্ঠ 2",
      "name": "Android Speech Recognition and Synthesis from Google bn-in-x-bnm-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google bn-in-x-bnm-local"
      ],
      "nativeID": [
        "bn-in-x-bnm-network",
        "bn-in-x-bnm-local"
      ],
      "language": "bn-IN",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "পুরুষ কন্ঠ",
      "name": "Google বাংলা (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google bn-bd-x-ban-network",
        "Chrome OS বাংলা",
        "Android Speech Recognition and Synthesis from Google bn-bd-x-ban-local",
        "Android Speech Recognition and Synthesis from Google bn-BD-language"
      ],
      "nativeID": [
        "bn-bd-x-ban-network",
        "bn-bd-x-ban-local"
      ],
      "language": "bn-BD",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    }
  ]
}

=== readium/speech/json/ru.json
{
  "language": "ru",
  "defaultRegion": "ru-RU",
  "testUtterance": "Здравствуйте, меня зовут {name} и я русский голос.",
  "voices": [
    {
      "label": "Svetlana",
      "name": "Microsoft Svetlana Online (Natural) - Russian (Russia)",
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Ekaterina",
      "name": "Microsoft Ekaterina Online - Russian (Russia)",
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Dmitry",
      "name": "Microsoft Dmitry Online (Natural) - Russian (Russia)",
      "language": "ru-RU",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Google женский голос",
      "name": "Google русский",
      "note": "This voice is pre-loaded in Chrome on desktop. Utterances that are longer than 14 seconds long can trigger a bug with this voice, check the notes in the project's README for more information.",
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "controls": {
        "boundary": false
      },
      "browser": [
        "ChromeDesktop"
      ],
      "preloaded": true
    },
    {
      "label": "Katya",
      "name": "Katya",
      "localizedName": "apple",
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Milena",
      "name": "Milena",
      "localizedName": "apple",
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Yuri",
      "name": "Yuri",
      "localizedName": "apple",
      "language": "ru-RU",
      "gender": "male",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Irina",
      "name": "Microsoft Irina - Russian (Russian)",
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Pavel",
      "name": "Microsoft Pavel - Russian (Russian)",
      "language": "ru-RU",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Женский голос 1",
      "name": "Android Speech Recognition and Synthesis from Google ru-ru-x-dfc-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ru-ru-x-dfc-local"
      ],
      "nativeID": [
        "ru-ru-x-dfc-network",
        "ru-ru-x-dfc-local"
      ],
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Женский голос 2",
      "name": "Android Speech Recognition and Synthesis from Google ru-ru-x-ruc-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ru-ru-x-ruc-local"
      ],
      "nativeID": [
        "ru-ru-x-ruc-network",
        "ru-ru-x-ruc-local"
      ],
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Женский голос 3",
      "name": "Android Speech Recognition and Synthesis from Google ru-ru-x-rue-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ru-ru-x-rue-local"
      ],
      "nativeID": [
        "ru-ru-x-rue-network",
        "ru-ru-x-rue-local"
      ],
      "language": "ru-RU",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Мужской голос 1",
      "name": "Android Speech Recognition and Synthesis from Google ru-ru-x-rud-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ru-ru-x-rud-local"
      ],
      "nativeID": [
        "ru-ru-x-rud-network",
        "ru-ru-x-rud-local"
      ],
      "language": "ru-RU",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Мужской голос 2",
      "name": "Android Speech Recognition and Synthesis from Google ru-ru-x-ruf-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ru-ru-x-ruf-local"
      ],
      "nativeID": [
        "ru-ru-x-ruf-network",
        "ru-ru-x-ruf-local"
      ],
      "language": "ru-RU",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    }
  ]
}

=== readium/speech/json/cs.json
{
  "language": "cs",
  "defaultRegion": "cs-CZ",
  "testUtterance": "Dobrý den, jmenuji se {name} a jsem český hlas.",
  "voices": [
    {
      "label": "Vlasta",
      "name": "Microsoft Vlasta Online (Natural) - Czech (Czech)",
      "language": "cs-CZ",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Antonin",
      "name": "Microsoft Antonin Online (Natural) - Czech (Czech)",
      "language": "cs-CZ",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Zuzana",
      "name": "Zuzana",
      "localizedName": "apple",
      "language": "cs-CZ",
      "gender": "female",
      "quality": [
        "low",
        "normal",
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Iveta",
      "name": "Iveta",
      "localizedName": "apple",
      "language": "cs-CZ",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Jakub",
      "name": "Microsoft Jakub - Czech (Czech)",
      "language": "cs-CZ",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Ženský hlas",
      "name": "Google čeština (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google cs-cz-x-jfs-network",
        "Chrome OS čeština",
        "Android Speech Recognition and Synthesis from Google cs-cz-x-jfs-local",
        "Android Speech Recognition and Synthesis from Google cs-CZ-language"
      ],
      "nativeID": [
        "cs-cz-x-jfs-network",
        "cs-cz-x-jfs-local"
      ],
      "language": "cs-CZ",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/kk.json
{
  "language": "kk",
  "defaultRegion": "kk-KZ",
  "testUtterance": "Сәлеметсіз бе, менің атым {name} және мен қазақ дауыстымын.",
  "voices": [
    {
      "label": "Aigul",
      "name": "Microsoft Aigul Online (Natural) - Kazakh (Kazakhstan)",
      "language": "kk-KZ",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Daulet",
      "name": "Microsoft Daulet Online (Natural) - Kazakh (Kazakhstan)",
      "language": "kk-KZ",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Aru",
      "name": "Aru",
      "nativeID": [
        "com.apple.voice.Aru"
      ],
      "localizedName": "apple",
      "language": "kk-KZ",
      "gender": "female",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    }
  ]
}

=== readium/speech/json/te.json
{
  "language": "te",
  "defaultRegion": "te-IN",
  "testUtterance": "హలో, నా పేరు {name} మరియు నేను తెలుగు వాణిని.",
  "voices": [
    {
      "label": "Shruti",
      "name": "Microsoft Shruti Online (Natural) - Telugu (India)",
      "language": "te-IN",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Mohan",
      "name": "Microsoft Mohan Online (Natural) - Telugu (India)",
      "language": "te-IN",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Geeta",
      "name": "Geeta",
      "localizedName": "apple",
      "language": "te-IN",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "స్త్రీ స్వరం",
      "name": "Android Speech Recognition and Synthesis from Google te-in-x-tef-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google te-in-x-tef-local",
        "Android Speech Recognition and Synthesis from Google te-IN-language"
      ],
      "nativeID": [
        "te-in-x-tef-network",
        "te-in-x-tef-local"
      ],
      "language": "te-IN",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "పురుష స్వరం",
      "name": "Android Speech Recognition and Synthesis from Google te-in-x-tem-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google te-in-x-tem-local"
      ],
      "nativeID": [
        "te-in-x-tem-network",
        "te-in-x-tem-local"
      ],
      "language": "te-IN",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    }
  ]
}

=== readium/speech/json/gl.json
{
  "language": "gl",
  "defaultRegion": "gl-ES",
  "testUtterance": "Ola, chámome {name} e son unha voz galega.",
  "voices": [
    {
      "label": "Sabela",
      "name": "Microsoft Sabela Online (Natural) - Galician",
      "language": "gl-ES",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Roi",
      "name": "Microsoft Roi Online (Natural) - Galician",
      "language": "gl-ES",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Carmela",
      "name": "Carmela",
      "localizedName": "apple",
      "language": "gl-ES",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    }
  ]
}

=== readium/speech/json/kn.json
{
  "language": "kn",
  "defaultRegion": "kn-IN",
  "testUtterance": "ಹಲೋ, ನನ್ನ ಹೆಸರು {name} ಮತ್ತು ನಾನು ಕನ್ನಡ ಧ್ವನಿ.",
  "voices": [
    {
      "label": "Sapna",
      "name": "Microsoft Sapna Online (Natural) - Kannada (India)",
      "language": "kn-IN",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Gagan",
      "name": "Microsoft Gagan Online (Natural) - Kannada (India)",
      "language": "kn-IN",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Soumya",
      "name": "Soumya",
      "localizedName": "apple",
      "language": "kn-IN",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "ಸ್ತ್ರೀ ಧ್ವನಿ",
      "name": "Android Speech Recognition and Synthesis from Google kn-in-x-knf-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google kn-in-x-knf-local",
        "Android Speech Recognition and Synthesis from Google kn-IN-language"
      ],
      "nativeID": [
        "kn-in-x-knf-network",
        "kn-in-x-knf-local"
      ],
      "language": "kn-IN",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "ಪುರುಷ ಧ್ವನಿ",
      "name": "Android Speech Recognition and Synthesis from Google kn-in-x-knm-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google kn-in-x-knm-local"
      ],
      "nativeID": [
        "kn-in-x-knm-network",
        "kn-in-x-knm-local"
      ],
      "language": "kn-IN",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    }
  ]
}
