=== readium/speech/voices.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://readium.org/speech/voices.schema.json",
  "title": "Recommended voices for TTS",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "language": {
      "type": "string"
    },
    "defaultRegion": {
      "type": "string"
    },
    "testUtterance": {
      "type": "string"
    },
    "voices": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "label": {
            "type": "string",
            "description": "Provides a human-friendly label for each voice."
          },
          "name": {
            "type": "string",
            "description": "Identifies voices, as returned by the Web Speech API."
          },
          "localizedName": {
            "type": "string",
            "description": "Identifies the string pattern used to localized a given voice.",
            "enum": [
              "android",
              "apple"
            ]
          },
          "note": {
            "type": "string"
          },
          "altNames": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Alternate names for a given voice. Only useful for Apple voices."
            }
          },
          "nativeID": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Identifiers used by the native API of the platform for a specific voice."
            }
          },
          "language": {
            "type": "string",
            "description": "BCP-47 language tag that identifies the language of a voice."
          },
          "altLanguage": {
            "type": "string",
            "description": "Alternative BCP-47 language tag, mostly used for deprecated values."
          },
          "otherLanguages": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "multiLingual": {
            "type": "boolean",
            "description": "Identifies voices that are capable of handling multiple languages, even if it means that the voice itself will change. Only available on Microsoft Natural voices for now.",
            "default": false
          },
          "gender": {
            "type": "string",
            "description": "Identifies the gender of a voice.",
            "enum": [
              "neutral",
              "female",
              "male"
            ]
          },
          "children": {
            "type": "boolean",
            "description": "Indicates if the voice is a children voice.",
            "default": false
          },
          "quality": {
            "type": "array",
            "description": "Quality available for the variants of a given voice",
            "items": {
              "type": "string",
              "enum": [
                "veryLow",
                "low",
                "normal",
                "high",
                "veryHigh"
              ]
            }
          },
          "rate": {
            "type": "number",
            "description": "Default recommended speed rate for a voice.",
            "minimum": 0.1,
            "maximum": 10,
            "default": 1
          },
          "pitch": {
            "type": "number",
            "description": "Default recommended pitch rate for a voice.",
            "minimum": 0,
            "maximum": 2,
            "default": 1
          },
          "controls": {
            "type": "object",
            "description": "Indicates which controls are available for a given voice.",
            "additionalProperties": false,
            "properties": {
              "boundary": {
                "description": "Indicates whether a voice returns boundary events.",
                "type": "boolean",
                "default": true
              },
              "pitch": {
                "description": "Indicates whether a voice can be pitch adjusted.",
                "type": "boolean",
                "default": true
              }
            }
          },
          "os": {
            "type": "array",
            "description": "List of operating systems in which a voice is available.",
            "minItems": 1,
            "items": {
              "type": "string",
              "enum": [
                "Android",
                "ChromeOS",
                "iOS",
                "iPadOS",
                "macOS",
                "Windows"
              ]
            }
          },
          "browser": {
            "type": "array",
            "description": "List of Web browsers in which a voice is available.",
            "minItems": 1,
            "items": {
              "type": "string",
              "enum": [
                "ChromeDesktop",
                "Edge",
                "Firefox",
                "Safari"
              ]
            }
          },
          "preloaded": {
            "type": "boolean",
            "description": "Indicates that a voice is preloaded in all OS and browsers that have been identified.",
            "default": false
          }
        },
        "required": [
          "name"
        ]
      }
    }
  },
  "required": [
    "voices"
  ]
}

=== readium/speech/json/ms.json
{
  "language": "ms",
  "defaultRegion": "ms-MY",
  "testUtterance": "Hello, nama saya {name} dan saya suara Melayu.",
  "voices": [
    {
      "label": "Yasmin",
      "name": "Microsoft Yasmin Online (Natural) - Malay (Malaysia)",
      "language": "ms-MY",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Osman",
      "name": "Microsoft Osman Online (Natural) - Malay (Malaysia)",
      "language": "ms-MY",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Amira",
      "name": "Amira",
      "localizedName": "apple",
      "language": "ms-MY",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Rizwan",
      "name": "Microsoft Rizwan - Malay (Malaysia)",
      "language": "ms-MY",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Suara perempuan 1",
      "name": "Android Speech Recognition and Synthesis from Google ms-my-x-msc-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ms-my-x-msc-local",
        "Android Speech Recognition and Synthesis from Google ms-MY-language"
      ],
      "nativeID": [
        "ms-my-x-msc-network",
        "ms-my-x-msc-local"
      ],
      "language": "ms-MY",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Suara perempuan 2",
      "name": "Android Speech Recognition and Synthesis from Google ms-my-x-mse-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ms-my-x-mse-local"
      ],
      "nativeID": [
        "ms-my-x-mse-network",
        "ms-my-x-mse-local"
      ],
      "language": "ms-MY",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Suara lelaki 1",
      "name": "Android Speech Recognition and Synthesis from Google ms-my-x-msd-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ms-my-x-msd-local"
      ],
      "nativeID": [
        "ms-my-x-msd-network",
        "ms-my-x-msd-local"
      ],
      "language": "ms-MY",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Suara lelaki 2",
      "name": "Android Speech Recognition and Synthesis from Google ms-my-x-msg-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google ms-my-x-msg-local"
      ],
      "nativeID": [
        "ms-my-x-msg-network",
        "ms-my-x-msg-local"
      ],
      "language": "ms-MY",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/nl.json
{
  "language": "nl",
  "defaultRegion": "nl-NL",
  "testUtterance": "Hallo, mijn naam is {name} en ik ben een Nederlandse stem.",
  "voices": [
    {
      "label": "Colette",
      "name": "Microsoft Colette Online (Natural) - Dutch (Netherlands)",
      "language": "nl-NL",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Fenna",
      "name": "Microsoft Fenna Online (Natural) - Dutch (Netherlands)",
      "language": "nl-NL",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Hanna",
      "name": "Microsoft Hanna Online - Dutch (Netherlands)",
      "language": "nl-NL",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Maarten",
      "name": "Microsoft Maarten Online (Natural) - Dutch (Netherlands)",
      "language": "nl-NL",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Dena",
      "name": "Microsoft Dena Online (Natural) - Dutch (Belgium)",
      "language": "nl-BE",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Arnaud",
      "name": "Microsoft Arnaud Online (Natural) - Dutch (Belgium)",
      "language": "nl-BE",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Google mannelijke stem",
      "name": "Google Nederlands",
      "note": "This voice is pre-loaded in Chrome on desktop. Utterances that are longer than 14 seconds long can trigger a bug with this voice, check the notes in the project's README for more information.",
      "language": "nl-NL",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "controls": {
        "boundary": false
      },
      "browser": [
        "ChromeDesktop"
      ],
      "preloaded": true
    },
    {
      "label": "Claire",
      "name": "Claire",
      "localizedName": "apple",
      "language": "nl-NL",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Xander",
      "name": "Xander",
      "localizedName": "apple",
      "language": "nl-NL",
      "gender": "male",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Ellen",
      "name": "Ellen",
      "localizedName": "apple",
      "language": "nl-BE",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Frank",
      "name": "Microsoft Frank - Dutch (Netherlands)",
      "language": "nl-NL",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Vrouwelijke stem 1 (Nederland)",
      "name": "Google Nederlands 4 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nl-nl-x-lfc-network",
        "Chrome OS Nederlands 4",
        "Android Speech Recognition and Synthesis from Google nl-nl-x-lfc-local",
        "Android Speech Recognition and Synthesis from Google nl-NL-language"
      ],
      "nativeID": [
        "nl-nl-x-lfc-network",
        "nl-nl-x-lfc-local"
      ],
      "language": "nl-NL",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Vrouwelijke stem 2 (Nederland)",
      "name": "Google Nederlands 1 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nl-nl-x-tfb-network",
        "Chrome OS Nederlands 1",
        "Android Speech Recognition and Synthesis from Google nl-nl-x-tfb-local"
      ],
      "nativeID": [
        "nl-nl-x-tfb-network",
        "nl-nl-x-tfb-local"
      ],
      "language": "nl-NL",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Vrouwelijke stem 3 (Nederland)",
      "name": "Google Nederlands 5 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nl-nl-x-yfr-network",
        "Chrome OS Nederlands 5",
        "Android Speech Recognition and Synthesis from Google nl-nl-x-yfr-local"
      ],
      "nativeID": [
        "nl-nl-x-yfr-network",
        "nl-nl-x-yfr-local"
      ],
      "language": "nl-NL",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Mannelijke stem 1 (Nederland)",
      "name": "Google Nederlands 2 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nl-nl-x-bmh-network",
        "Chrome OS Nederlands 2",
        "Android Speech Recognition and Synthesis from Google nl-nl-x-bmh-local"
      ],
      "nativeID": [
        "nl-nl-x-bmh-network",
        "nl-nl-x-bmh-local"
      ],
      "language": "nl-NL",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Mannelijke stem 2 (Nederland)",
      "name": "Google Nederlands 3 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nl-nl-x-dma-network",
        "Chrome OS Nederlands 3",
        "Android Speech Recognition and Synthesis from Google nl-nl-x-dma-local"
      ],
      "nativeID": [
        "nl-nl-x-dma-network",
        "nl-nl-x-dma-local"
      ],
      "language": "nl-NL",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Vrouwelijke stem (België)",
      "name": "Android Speech Recognition and Synthesis from Google nl-be-x-bec-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nl-be-x-bec-local",
        "Android Speech Recognition and Synthesis from Google nl-BE-language"
      ],
      "nativeID": [
        "nl-be-x-bec-network",
        "nl-be-x-bec-local"
      ],
      "language": "nl-BE",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "Mannelijke stem (België)",
      "name": "Android Speech Recognition and Synthesis from Google nl-be-x-bed-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nl-be-x-bed-local"
      ],
      "nativeID": [
        "nl-be-x-bed-network",
        "nl-be-x-bed-local"
      ],
      "language": "nl-BE",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/nb.json
{
  "language": "nb",
  "defaultRegion": "nb-NO",
  "testUtterance": "Hei, jeg heter {name} og er en norsk stemme.",
  "voices": [
    {
      "label": "Pernille",
      "name": "Microsoft Pernille Online (Natural) - Norwegian (Bokmål, Norway)",
      "language": "nb-NO",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Finn",
      "name": "Microsoft Finn Online (Natural) - Norwegian (Bokmål Norway)",
      "language": "nb-NO",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Nora",
      "name": "Nora",
      "localizedName": "apple",
      "language": "nb-NO",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Henrik",
      "name": "Henrik",
      "localizedName": "apple",
      "language": "nb-NO",
      "gender": "male",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ]
    },
    {
      "label": "Jon",
      "name": "Microsoft Jon - Norwegian (Bokmål Norway)",
      "language": "nb-NO",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "Kvinnestemme 1",
      "name": "Google Norsk Bokmål 2 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nb-no-x-cfl-network",
        "Chrome OS Norsk Bokmål 2",
        "Android Speech Recognition and Synthesis from Google nb-no-x-cfl-local",
        "Android Speech Recognition and Synthesis from Google nb-NO-language"
      ],
      "nativeID": [
        "nb-no-x-cfl-network",
        "nb-no-x-cfl-local"
      ],
      "language": "nb-NO",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Kvinnestemme 2",
      "name": "Google Norsk Bokmål 1 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nb-no-x-rfj-network",
        "Chrome OS Norsk Bokmål 1",
        "Android Speech Recognition and Synthesis from Google nb-no-x-rfj-local"
      ],
      "nativeID": [
        "nb-no-x-rfj-network",
        "nb-no-x-rfj-local"
      ],
      "language": "nb-NO",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Kvinnestemme 3",
      "name": "Google Norsk Bokmål 4 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nb-no-x-tfs-network",
        "Chrome OS Norsk Bokmål 4",
        "Android Speech Recognition and Synthesis from Google nb-no-x-tfs-local"
      ],
      "nativeID": [
        "nb-no-x-tfs-network",
        "nb-no-x-tfs-local"
      ],
      "language": "nb-NO",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Mannsstemme 1",
      "name": "Google Norsk Bokmål 3 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nb-no-x-cmj-network",
        "Chrome OS Norsk Bokmål 3",
        "Android Speech Recognition and Synthesis from Google nb-no-x-cmj-local"
      ],
      "nativeID": [
        "nb-no-x-cmj-network",
        "nb-no-x-cmj-local"
      ],
      "language": "nb-NO",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    },
    {
      "label": "Mannsstemme 2",
      "name": "Google Norsk Bokmål 5 (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google nb-no-x-tmg-network",
        "Chrome OS Norsk Bokmål 5",
        "Android Speech Recognition and Synthesis from Google nb-no-x-tmg-local"
      ],
      "nativeID": [
        "nb-no-x-tmg-network",
        "nb-no-x-tmg-local"
      ],
      "language": "nb-NO",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true,
      "controls": {
        "boundary": false
      }
    }
  ]
}

=== readium/speech/json/he.json
{
  "language": "he",
  "defaultRegion": "he-IL",
  "testUtterance": "שלום, שמי {name} ואני קול עברי.",
  "voices": [
    {
      "label": "Hila",
      "name": "Microsoft Hila Online (Natural) - Hebrew (Israel)",
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Avri",
      "name": "Microsoft Avri Online (Natural) - Hebrew (Israel)",
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false
      }
    },
    {
      "label": "Carmit",
      "name": "Carmit",
      "localizedName": "apple",
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Asaf",
      "name": "Microsoft Asaf - Hebrew (Israel)",
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "male",
      "quality": [
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Windows"
      ],
      "preloaded": true
    },
    {
      "label": "קול גברי 1",
      "name": "Android Speech Recognition and Synthesis from Google he-il-x-heb-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google he-il-x-heb-local",
        "Android Speech Recognition and Synthesis from Google he-IL-language"
      ],
      "nativeID": [
        "he-il-x-heb-network",
        "he-il-x-heb-local"
      ],
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "קול נשי 1",
      "name": "Android Speech Recognition and Synthesis from Google he-il-x-hec-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google he-il-x-hec-local"
      ],
      "nativeID": [
        "he-il-x-hec-network",
        "he-il-x-hec-local"
      ],
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "קול גברי 2",
      "name": "Android Speech Recognition and Synthesis from Google he-il-x-hed-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google he-il-x-hed-local"
      ],
      "nativeID": [
        "he-il-x-hed-network",
        "he-il-x-hed-local"
      ],
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "male",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    },
    {
      "label": "קול נשי 2",
      "name": "Android Speech Recognition and Synthesis from Google he-il-x-hee-network",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google he-il-x-hee-local"
      ],
      "nativeID": [
        "he-il-x-hee-network",
        "he-il-x-hee-local"
      ],
      "language": "he-IL",
      "altLanguage": "iw-IL",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}

=== readium/speech/json/uk.json
{
  "language": "uk",
  "defaultRegion": "uk-UA",
  "testUtterance": "Здравствуйте, меня зовут {name} и я украинский голос.",
  "voices": [
    {
      "label": "Polina",
      "name": "Microsoft Polina Online (Natural) - Ukrainian (Ukraine)",
      "language": "uk-UA",
      "gender": "female",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Ostap",
      "name": "Microsoft Ostap Online (Natural) - Ukrainian (Ukraine)",
      "language": "uk-UA",
      "gender": "male",
      "quality": [
        "veryHigh"
      ],
      "rate": 1,
      "browser": [
        "Edge"
      ],
      "preloaded": true,
      "controls": {
        "pitch": false,
        "boundary": false
      }
    },
    {
      "label": "Lesya",
      "name": "Lesya",
      "localizedName": "apple",
      "language": "uk-UA",
      "gender": "female",
      "quality": [
        "low",
        "normal"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "macOS",
        "iOS",
        "iPadOS"
      ],
      "preloaded": true
    },
    {
      "label": "Жіночий голос",
      "name": "Google українська (Natural)",
      "altNames": [
        "Android Speech Recognition and Synthesis from Google uk-ua-x-hfd-network",
        "Chrome OS українська",
        "Android Speech Recognition and Synthesis from Google uk-ua-x-hfd-local",
        "Android Speech Recognition and Synthesis from Google uk-UA-language"
      ],
      "nativeID": [
        "uk-ua-x-hfd-network",
        "uk-ua-x-hfd-local"
      ],
      "language": "uk-UA",
      "gender": "female",
      "quality": [
        "high"
      ],
      "rate": 1,
      "pitch": 1,
      "os": [
        "Android",
        "ChromeOS"
      ],
      "preloaded": true
    }
  ]
}
